// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Hello = 0;

var Counter = 0;

var Todo = 0;

var TodoType = 0;

exports.Hello = Hello;
exports.Counter = Counter;
exports.Todo = Todo;
exports.TodoType = TodoType;
/* No side effect */
