// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var fontSize_ = Css.rem(0.9);

var commentItem = Css.style(/* :: */[
      Css.margin2(Css.rem(0.5), Css.rem(0.0)),
      /* [] */0
    ]);

var commentUsername = Css.style(/* :: */[
      Css.fontSize(fontSize_),
      /* :: */[
        Css.marginRight(Css.ch(1.0)),
        /* :: */[
          Css.display(Css.inline),
          /* [] */0
        ]
      ]
    ]);

var commentText = Css.style(/* :: */[
      Css.fontSize(fontSize_),
      /* :: */[
        Css.display(Css.inline),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* fontSize_ */fontSize_,
  /* commentItem */commentItem,
  /* commentUsername */commentUsername,
  /* commentText */commentText
];

var component = ReasonReact.statelessComponent("Comment");

function make(username, text, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("li", {
                          className: commentItem
                        }, React.createElement("h4", {
                              className: commentUsername
                            }, username), React.createElement("p", {
                              className: commentText
                            }, text));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.username, jsProps.text, /* array */[]);
      }));

export {
  Styles ,
  component ,
  make ,
  jsComponent ,
  
}
/* fontSize_ Not a pure module */
