/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const CommentBS = require('./Comment.bs');

// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const ReasonReact = require('reason-react/src/ReasonReact.js');

// tslint:disable-next-line:interface-over-type-literal
export type Props = {
  readonly username: string; 
  readonly text: string; 
  readonly children?: unknown
};

export const Comment: React.ComponentClass<Props> = ReasonReact.wrapReasonForJs(
  CommentBS.component,
  (function _(jsProps: Props) {
     return Curry._3(CommentBS.make, jsProps.username, jsProps.text, jsProps.children);
  }));

export default Comment;
